
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

group:
  inhabitants:
    name: "Bewohner"
    entities:
      - person.clemens
      - person.carola

template:
  - binary_sensor:
    - name: "Presence Toilette"
      unique_id: 'presence_toilette'
      state: >
        {% set motion_entity = states.binary_sensor.bewegungsmelder_toilette_bewegung %}
        {% if motion_entity is not none %}
          {% if motion_entity.state == 'on' %}
            true
          {% else %}
            {{ ( now()|as_timestamp() - motion_entity.last_changed|as_timestamp() ) < 60 }}
          {% endif %}
        {% else %}
          false
        {% endif %}
      device_class: occupancy
      
  - binary_sensor:
      - name: "Ankunft"
        unique_id: 'presence_entrance'
        state: >
          {% set device_ids = [
            'device_tracker.pixel_7_pro'
          ] %}

          {% set any_just_arrived = false %}
          {% for dev_id in device_ids %}
            {% set dev = states[dev_id] %}
            {% if dev is not none and dev.state == 'home' %}
              {% set diff = now()|as_timestamp() - dev.last_changed|as_timestamp() %}
              {% if diff < 180 %}
                {% set any_just_arrived = true %}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ any_just_arrived }}
        device_class: presence
    
  - sensor:
    - name: "Helligkeit Wohnzimmer"
      unique_id: light_intensity_wohnzimmer
      state: >
        {% set lux = states('sensor.light_level_wohnzimmer') | float %}
        {% if lux < 100 %}
          dark
        {% elif lux < 150 %}
          sufficient
        {% else %}
          bright
        {% endif %}