
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
automation toilette: !include_dir_list toilette/automations/
automation wohnzimmer: !include_dir_list wohnzimmer/automations/
automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
script wohnzimmer: !include_dir_named wohnzimmer/scripts/
scene: !include scenes.yaml

group:
  inhabitants:
    name: "Bewohner"
    entities:
      - person.clemens
      - person.carola

input_number:
  esstisch_default_brightness:
    name: Standard Esstisch-Helligkeit
    initial: 0
    min: 0
    max: 255
    step: 1

template: !include templates.yaml