- alias: "Aktiviere Lichtszenen basierend auf Präsenz und Tageszeit"
  triggers:
  # Trigger 1: Präsenz erkannt
  - trigger: state
    entity_id: binary_sensor.presence_wohnzimmer
    to: "on"
  # Trigger 2: Wechsel der Tageszeitschwelle
  - trigger: time
    at:
      - "07:00:00"
      - "17:00:00"
      - "20:00:00"
      - "22:00:00"
  action:
    - variables:
        transition_time: >
          {% if trigger.platform == 'state' %}
            3 
          {% elif trigger.platform == 'time' %}
            300
          {% else %}
            0 
          {% endif %}
    - choose:
        # Untertags (07:00 - 17:00)
        - conditions:
            - condition: time
              after: "07:00:00"
              before: "17:00:00"
          sequence:
            - action: scene.turn_on
              target:
                entity_id: scene.wohnzimmer_morgendammerung
        # Abendessen (17:00 - 20:00)
        - conditions:
            - condition: time
              after: "17:00:00"
              before: "20:00:00"
          sequence:
            - action: scene.turn_on
              target:
                entity_id: scene.wohnzimmer_abendessen_savanne
        # Später Abend (20:00 - 22:00)
        - conditions:
            - condition: time
              after: "18:00:00"
              before: "23:00:00"
          sequence:
            - action: scene.turn_on
              target:
                entity_id: scene.wohnzimmer_abend_arbeit
        # Nachtszene (22:00 - 06:00)
        - conditions:
            - condition: time
              after: "23:00:00"
              before: "06:00:00"
          sequence:
            - action: scene.turn_on
              target:
                entity_id: scene.wohnzimmer_nightlight

- alias: Esstischlicht hell bei Anwesenheit
  id: '1733732407539'
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.presence_esstisch
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_boolean.partymodus
    state: 'off'
  actions:
  - variables:
      current_brightness: "{{ state_attr('light.esstisch', 'brightness') | default(0) }}"
  - action: input_number.set_value
    target:
      entity_id: input_number.esstisch_previous_brightness
    data:
      value: "{{ current_brightness }}"
  - action: light.turn_on
    target:
      entity_id: light.esstisch
    data:
      brightness: "{{ [[current_brightness * 1.5 | round(0), 255] | min, 80] | max }}"
      transition: 10
  mode: single

- alias: "Esstisch keine Präsenz mehr"
  trigger:
  - trigger: state
    entity_id: binary_sensor.presence_esstisch
    to: "off"
  action:
  - action: light.turn_on
    target:
      entity_id: light.esstisch
    data:
      brightness: "{{ states('input_number.esstisch_previous_brightness') | int }}"
      transition: 10

- alias: Wohnzimmerlicht aus, wenn nicht benötigt
  id: '1733742144480'
  description: 'Läuft, wenn alle den Raum verlassen haben oder wenn Ida mit der Reinigung fertig ist.'
  triggers:
  - trigger: state
    entity_id: binary_sensor.presence_wohnzimmer
    to: 'off'
  - trigger: state
    entity_id: vacuum.ida
    to: 'docked'
  conditions:
  - condition: state
    entity_id: binary_sensor.presence_wohnzimmer
    state: 'off'
  - condition: state
    entity_id: vacuum.ida
    state: 'docked'
  actions:
  - action: light.turn_off
    target:
      area_id: wohnzimmer
  mode: single
- alias: Wohnzimmerlicht aus, wenn hell genug
  triggers:
  - trigger: state
    entity_id: sensor.light_intensity_wohnzimmer
    to: bright
  actions:
  - action: light.turn_off
    target:
      area_id: wohnzimmer
  mode: single

  